theme: minima
title: What is Life?
author: carat
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Being a CARAT starts from the middle of April this year. I was told to love myself, and create my own life.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
